### PR TITLE
Refarctored Endpoint Tags

### PR DESCRIPTION
**Pull request by MarcoB95-lab**
In this pull request, we've made improvements to our API documentation by implementing Swagger tags within the controller file. These additions help better categorize and organize our API endpoints, leading to an improved user experience for developers interacting with our documentation.

@bobo-k2  made a new pull request, because I had issues with the last one. Hope this are all the changes now. Please review it.

### CODE REVIEW

**Comment by bobo-k2** [comment]
HI @MarcoB95-lab thank you for your contribution. The PR looks good, but there is one small thing you need to do before merge. Style checks are failing so please run `yarn lint --fix` and commit changes.

**Review by impelcrypto — APPROVED** [review]

**Comment by MarcoB95-lab** [comment]
Hey @bobo-k2 thanks for the reply. I have added the fix and commited the code. Could you check, if it works now as you have intented it to?

**Review by bobo-k2 — APPROVED** [review]
LGTM

**Review by bobo-k2 — APPROVED** [review]
LGTM

**Comment by bobo-k2** [comment]
cc @togamamora

**Comment by togamamora** [comment]
@MarcoB95-lab 

This will be categorized as Tier3. Please provide your ASTR address.

**Comment by MarcoB95-lab** [comment]
Thank you very much @togamamora and @bobo-k2.
Here is my address:
PolkadotJS Wallet: WmZGLTdBevkUecmjmFB6hoN47imhrLERXhxsHxxjYGTJuTZ

**Comment by togamamora** [comment]
@bobo-k2 @Kahonnohak 

On a scale of 1-5, how would you rate this?

image

**Comment by bobo-k2** [comment]
> @bobo-k2 @Kahonnohak
> 
> On a scale of 1-5, how would you rate this?
> 
> image

It is 5. There was a minor comment on PR

**Comment by togamamora** [comment]
Thanks!!

**Pull request merged**
