### PR TITLE
Refactored endpoint tags

### PR DESCRIPTION
**Pull request by MarcoB95-lab**
Refactored endpoint tags to enhance organization and accurately categorize endpoints within their respective domains.

### CODE REVIEW

**Comment by MarcoB95-lab** [comment]
Refactored endpoint tags to enhance organization and accurately categorize endpoints within their respective domains.

**Comment by bobo-k2** [comment]
Hi @MarcoB95-lab thank you for you contribution. Please add comments to controllers code (e.g. https://github.com/AstarNetwork/astar-token-api/blob/5510d78abb964a3d50516bf512a97903f86c7205/src/controllers/DappsStakingController.ts#L33) since `swagger.json` is autogenerated file and it would be overwritten on next build.
After you add comments to controllers run `yarn build:swagger` to build Swagger documentation

**Comment by MarcoB95-lab** [comment]
Hey @bobo-k2, I'm currently working on the task, but I've encountered a few additional steps that need to be addressed. When I clone the repo and run "yarn build:swagger", the endpoint "api/v1/token/price/{symbol}" doesn't display a description, seemingly due to an issue with the controllers (e.g. TokenStatsController.ts).

Interestingly, the issue seems to be related to the presence of the "try" block in the controller. When I remove the "try" block and leave only the res.json... part, similar to the /api/v1/:network/token/price/:period endpoint, the description reappears, and I can successfully assign a tag.

`            try {
                res.json(await this._priceProvider.getUsdPrice(req.params.symbol));
            } catch (err) {
                this.handleError(res, err as Error);
            }`


Another solution would be to delete the unused endpoint "/api/token/stats" then the description reappers aswell and I can assign a tag.

**Comment by bobo-k2** [comment]
Hi @MarcoB95-lab I can't reproduce the issue you mentioned. When I add `#swagger.tags = ['Dapps Staking']` to a controller method, `swagger.json` is properly updated on `yarn build:swagger`

Regarding  "api/v1/token/price/{symbol}" endpoint, I also don't see an issue there. Added tags in the documentation and got the following output
```
"/api/v1/token/price/{symbol}": {
      "get": {
        "tags": [
          "Token"
        ],
        "description": "Retrieves current token price",
        "parameters": [
          {
            "name": "symbol",
            "in": "path",
            "required": true,
            "type": "string",
            "description": "Token symbol (eg. ASTR or SDN)"
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          }
        }
      }
```
Most likely the main reason for your issue is that you manually modified `swagger.json` file. Try deleting the file and regenerating it again.

**Comment by MarcoB95-lab** [comment]
What about the endpoints:

/api/v1/:network/dapps-staking/stats/transactions
/api/v1/:network/dapps-staking/stats/uaw
/api/v1/:network/dapps-staking/stats/nexteraeta

They are not displayed on the https://api.astar.network/ website, but are now displayed when I clone the repo and run it locally.
Should I ignore them with "// #swagger.ignore = true"?


Can I maybe have your TG so its easier to communicate?

**Comment by bobo-k2** [comment]
> What about the endpoints:

Please do not ignore endpoints above. Most likely GitHub CI action didn't trigger to generate Swagger documentation for those new endpoints. I will check why documentation autogeneration didn't trigger.
Let's keep communication here, to be visible to everyone.

**Pull request closed without merging**
