### PR TITLE
Uplift direct dependencies and fixed compilation issues

### PR DESCRIPTION
**Pull request by bobo-k2**

### CODE REVIEW

**Review by gluneau — CHANGES_REQUESTED** [review]
May need a `.d.ts` file

```
$ node src/swagger.js
Swagger-autogen:  Success ✔ 
[INFO] 10:09:14 ts-node-dev ver. 1.1.8 (using ts-node ver. 9.1.1, typescript ver. 4.5.5)
Compilation error in /home/gluneau/GitHub/astar/astar-token-api/src/modules/tx-query/utils/index.ts
[ERROR] 10:09:19 ⨯ Unable to compile TypeScript:
src/modules/tx-query/utils/index.ts:4:24 - error TS7016: Could not find a declaration file for module 'abi-decoder'. '/home/gluneau/GitHub/astar/astar-token-api/node_modules/abi-decoder/index.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/abi-decoder` if it exists or add a new declaration (.d.ts) file containing `declare module 'abi-decoder';`

4 import abiDecoder from 'abi-decoder';
```

**Comment by impelcrypto** [comment]
> May need a .d.ts file

Pushed, please take a look at [this](https://github.com/AstarNetwork/astar-token-api/pull/98) PR.

**Comment by impelcrypto** [comment]
'Unit Tests' failed

**Review by impelcrypto — APPROVED** [review]
It works

**Comment by bobo-k2** [comment]
> 'Unit Tests' failed

Fixed. Thank you

**Review by gluneau — APPROVED** [review]
works, LGTM.

**Pull request merged**
