### PR TITLE
feat: added an endpoint for fetching the transfer history details

### PR DESCRIPTION
**Pull request by impelcrypto**
* feat: added an endpoint for fetching the transfer history details
  * e.g.: /api/v1/shiden/tx/transfer?hash=0x8d4ab77f009ab3a7058ef3bb6bc853859c37e8af1836c2cbe99736ba4c7a098a 

image

Screenshot 2022-08-27 at 8 48 29 PM

Screenshot 2022-08-27 at 8 50 45 PM

Screenshot 2022-08-27 at 8 48 01 PM

### CODE REVIEW

**Comment by impelcrypto** [comment]
Hi @niklabh , the staging URL doesn't reflect the code changes, could you take a look?

https://astar-token-api--pr41-feat-endpath-transfe-h4ab3hr6.web.app/api/v1/shiden/tx/transfer?hash=0x8d4ab77f009ab3a7058ef3bb6bc853859c37e8af1836c2cbe99736ba4c7a098a

Also, it looks like `firebase deploy` was failed in the developing branch.

image

**Comment by niklabh** [comment]
checking

**Review by bobo-k2 — CHANGES_REQUESTED** [review]
Can you please write tests for the logic you added.

**Comment by impelcrypto** [comment]
@bobo-k2 @niklabh 
Do you know how to pass this test properly? The error is because the app cannot find the `apiKey` that should be returned by firebase. Btw, all tests have passed on my laptop.

https://github.com/AstarNetwork/astar-token-api/runs/8058794346?check_suite_focus=true#step:4:58

https://github.com/AstarNetwork/astar-token-api/blob/464277ba09eac70e84b44eea01a629bf7db2d9c1/src/utils.ts#L65

image

**Comment by bobo-k2** [comment]
If I see correctly TxQueryService tests are failing. If your intention is to write unit test for this service you can mock FirebaseService.

**Comment by impelcrypto** [comment]
@bobo-k2 @niklabh 
I've added getSubscanOption function in [mock file](https://github.com/AstarNetwork/astar-token-api/pull/41/commits/1edc4d1be27828b3cba8f88d8662ae39061159dc#diff-ac3a77104545bbb8ce4138da0fb924dad2ba9b392d78819b874770a11b378c95R16) but still got an error related to apiKey.

https://github.com/AstarNetwork/astar-token-api/runs/8066053520?check_suite_focus=true#step:4:57

**Comment by impelcrypto** [comment]
Actually, I thought [fetchSubscan](https://github.com/AstarNetwork/astar-token-api/blob/1edc4d1be27828b3cba8f88d8662ae39061159dc/tests/services/AstarApiMock.ts#L84) in the mock file is enough to test [fetchTransferDetails function](https://github.com/AstarNetwork/astar-token-api/blob/feat/endpath-transfer-history/src/services/TxQueryService.ts#L42) since the mock file returns the mocked reply

**Comment by impelcrypto** [comment]
Hi @bobo-k2 

> TypeError: Reflect.hasOwnMetadata is not a function

Do you know how to avoid this error? I think this is something related to `inversify`

image

**Comment by bobo-k2** [comment]
> Hi @bobo-k2
> 
> > TypeError: Reflect.hasOwnMetadata is not a function
> > Do you know how to avoid this error? I think this is related to `inversify`
> 
Yes it is. Try adding `import 'reflect-metadata';` as the first line in your test file

**Review by bobo-k2 — APPROVED** [review]
LGTM

**Pull request merged**
